spring:
  #环境dev/pro
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 512MB # 单个文件大小
      max-request-size: 512MB # 设置总上传的数据大小
      enabled: true #开启


logging:
  level:
    org.springframework.web: INFO